/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zilliz_spark_connector_jni_MilvusStorageJNI */

#ifndef _Included_com_zilliz_spark_connector_jni_MilvusStorageJNI
#define _Included_com_zilliz_spark_connector_jni_MilvusStorageJNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    createSpace
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_createSpace
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    writeData
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_writeData
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readData
 * Signature: (J[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readData
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    readDataWithFilter
 * Signature: (J[Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_readDataWithFilter
  (JNIEnv *, jclass, jlong, jobjectArray, jstring);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getSpaceVersion
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getSpaceVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    getStorageSize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_getStorageSize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    closeSpace
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_closeSpace
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zilliz_spark_connector_jni_MilvusStorageJNI
 * Method:    deleteSpace
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zilliz_spark_connector_jni_MilvusStorageJNI_00024_deleteSpace
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
